# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Z7u7BB-wBP0e4BDq1IM_GCwCVl67O4u
"""

import sqlite3
from IPython.display import clear_output

# =============================
# Database Functions
# =============================
def init_db():
    conn = sqlite3.connect("tasks.db")
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS tasks (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT,
                    status TEXT DEFAULT 'pending'
                )''')
    conn.commit()
    conn.close()

def add_task(title):
    conn = sqlite3.connect("tasks.db")
    c = conn.cursor()
    c.execute("INSERT INTO tasks (title) VALUES (?)", (title,))
    conn.commit()
    conn.close()

def get_all_tasks():
    conn = sqlite3.connect("tasks.db")
    c = conn.cursor()
    c.execute("SELECT * FROM tasks")
    tasks = c.fetchall()
    conn.close()
    return tasks

def update_status(task_id, new_status):
    conn = sqlite3.connect("tasks.db")
    c = conn.cursor()
    c.execute("UPDATE tasks SET status=? WHERE id=?", (new_status, task_id))
    conn.commit()
    conn.close()

def delete_task(task_id):
    conn = sqlite3.connect("tasks.db")
    c = conn.cursor()
    c.execute("DELETE FROM tasks WHERE id=?", (task_id,))
    conn.commit()
    conn.close()

# =============================
# Helper Functions
# =============================
def filter_tasks(status=None):
    tasks = get_all_tasks()
    if status:
        return [t for t in tasks if t[2] == status]
    return tasks

# =============================
# CLI Interface
# =============================
def menu():
    print("\n===== Task Manager =====")
    print("1. Add new task")
    print("2. View all tasks")
    print("3. Filter tasks by status")
    print("4. Update task status")
    print("5. Delete a task")
    print("6. Exit")
    print("========================")

def main():
    init_db()

    while True:
        menu()
        choice = input("Choose an option (1-6): ")

        if choice == "1":
            title = input("Enter task title: ")
            add_task(title)
            clear_output()
            print(f"✅ Task '{title}' added successfully!")

        elif choice == "2":
            clear_output()
            tasks = get_all_tasks()
            if tasks:
                print("\nAll Tasks:")
                for t in tasks:
                    print(f"[{t[0]}] {t[1]} - {t[2]}")
            else:
                print("⚠️ No tasks found.")

        elif choice == "3":
            status = input("Enter status to filter (pending/done): ").lower()
            clear_output()
            tasks = filter_tasks(status)
            if tasks:
                print(f"\nTasks with status '{status}':")
                for t in tasks:
                    print(f"[{t[0]}] {t[1]} - {t[2]}")
            else:
                print("⚠️ No tasks found with that status.")

        elif choice == "4":
            task_id = int(input("Enter task ID to update: "))
            new_status = input("Enter new status (pending/done): ").lower()
            update_status(task_id, new_status)
            clear_output()
            print(f"✅ Task {task_id} updated to '{new_status}'.")

        elif choice == "5":
            task_id = int(input("Enter task ID to delete: "))
            delete_task(task_id)
            clear_output()
            print(f"🗑️ Task {task_id} deleted successfully!")

        elif choice == "6":
            clear_output()
            print("👋 Exiting program... Bye!")
            break

        else:
            clear_output()
            print("❌ Invalid option. Please choose 1-6.")

main()